### ISSUE TITLE
Incorporate application-specific onboarding flow when attaching applications to a source

### ISSUE THREAD

**Issue by dccurtis** [RedHatInsights/sources-ui#189]
The source creation onboarding wizard flows allow for per-app wizard screens when attaching an application. For example: Create AWS Source with Cost Management attached, the user is prompted to enter the S3 bucket.

The app-specific UI pages are missing when attaching an application to a pre-existing source via the `...` -> `Manage applications` screen.

Changes are needed for AWS, OCP, and Azure

UX considerations should be made for how the user would reuse some of the data that was already added when the source was initially created.

The most complicated situation is AWS.  For example, here are some questions that come to mind:
* The roleARN can be added when creating an AWS source, Cost Management needs this, should it reuse the one already added or should it be given an opportunity to be changed?  What's the impact of this to other applications if its changed
* How should the user handle the fact that they can not see the current roleARN due to backend implementation details?
* If the source had a AWS Secret added and no roleARN, we would need them to add a roleARN for Cost Management since we do not currently support AWS secret keys.  Are there any sources backend implications to having both an AWS secret and a roleARN?

FYI: @nlcwong

**Comment by rvsia** [comment]
https://github.com/RedHatInsights/sources-ui/pull/168

The work in progress version works following way:

1. It checks which authentication types are supported
A. If the source has already supported authentication type, these values are prefilled in the form, except the password we cannot get by the API, which will be no longer required > the authentication record will be updated

(So the ARN can be changed, but not modified, because it is a password value, same as in the edit form)

B. If not, values are empty and user has to enter new ones > a new authentication record is created

All other values (endpoint, billing source) are prefilled, if they already exist.

This approach will allow us to make the smallest number of changes in the code as possible when adding/editing the flow (Actually, no changes at all!)

**Comment by nlcwong** [comment]
@rvsia do you have a mock that would show us all what you said in the above post?

**Comment by rvsia** [comment]
Closed by https://github.com/RedHatInsights/sources-ui/pull/168
